### ISSUE TITLE
Enabling Dark Mode

### ISSUE THREAD

**Issue by Shardith** [ViTulyankin/Recolourful-Containers-GUI#2]
![image](https://github.com/user-attachments/assets/7af6f537-ba39-4527-84d5-88d5d755a14b)
The changelog for 1.1.1 states that dark mode was added (Yay!!!)

However I'm not sure how to enable/activate it. All container elements in the downloaded pack is still in light mode.

**Comment by ViTulyankin** [comment]
@Shardith, you can download dark version [here](https://www.curseforge.com/minecraft/texture-packs/recolourful-containers-gui-hud-dark)
